### PR TITLE
python: Add OpenTelemetry support

### PR DESCRIPTION
**Pull request by aabmass**
Add support for OpenTelemetry trace context in python.

- OpenTelemetry only supports python3+, so there is some complication there around the test code.
- If the user tries to use OpenCenus AND OpenTelemetry, we log a warning since they write to the same sql comment
- Passing tox tests run locally for python 2.7, 3.5, 3.6, and 3.7
- Tested psycopg2 manually with a script writing to cloud monitoring. See next PR https://github.com/google/sqlcommenter/pull/39

### CODE REVIEW

**Review by odeke-em — APPROVED** [review]
Thank you @aabmass, looks good but with a question and also let’s explicitly document the fact that Python2 won’t be supported for OpenTelemetry, but anyways Django support is deliberately for Python3+ as Python2 is no longer supported even on many systems.

**Comment by aabmass** [comment]
> let’s explicitly document the fact that Python2 won’t be supported for OpenTelemetry

Where should I do this?

**Comment by odeke-em** [comment]
>Where should I do this?

In the README in the Python section.

**Comment by aabmass** [comment]
@odeke-em added in 6ed6e406bcd5b64522a48b01a9ec170843588f15, lmk how that looks

**Pull request merged**
