### PR TITLE
Fix gradle build

### PR DESCRIPTION
**Pull request by nilebox**
1. Gradle Wrapper is missing the file `gradle/wrapper/gradle-wrapper.jar`:
```
./gradlew build
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

2. ErrorProne plugin is missing a dependency in `build.gradle` (see https://github.com/tbroyer/gradle-errorprone-plugin#usage):
```
/gradlew build
> Task :compileJava FAILED

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.ClassNotFoundException: com.google.errorprone.ErrorProneCompiler$Builder
```

After fixing the issues above, the build works with no issues:
```
./gradlew clean build

> Task :compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

BUILD SUCCESSFUL in 13s
11 actionable tasks: 11 executed

```

### CODE REVIEW

**Review by odeke-em — APPROVED** [review]
LGTM, thank you @nilebox!

**Comment by nilebox** [comment]
Thanks @odeke-em !

Are there any plans for adding a CI build for this repo? Any preference (GitHub Actions, CircleCI etc) or help needed?

For context, I am a member of OpenTelemetry team at Google, and I'm hosting an intern who will work on adding support for OpenTelemetry span context (in addition to already supported OpenCensus span context) to SQL Commenter.

**Comment by odeke-em** [comment]
Thank you @nilebox! Would be nice, but currently out of time/scope for me. Let me kindly ask @balachandr to take a look and prioritize resources for this.

**Pull request merged**
