### PR TITLE
Use async hooks from node, fix route comment

### LINKED ISSUE #24: Express middleware can write the wrong route
This effects both sequelize and knex as they use the same mechanism. The middleware sets the current request on the global `Knex` object:
https://github.com/google/sqlcommenter/blob/0e873a7df158ffa7ac6d0bd20664348452028a51/nodejs/sqlcommenter-nodejs/packages/sqlcommenter-knex/index.js#L154-L155

And then uses this request in the wrapped query function to get route information
https://github.com/google/sqlcommenter/blob/0e873a7df158ffa7ac6d0bd20664348452028a51/nodejs/sqlcommenter-nodejs/packages/sqlcommenter-knex/index.js#L70-L72

However, if the middleware runs again for a different concurrent request to a different route before the actual handler does the querying, it will overwrite `Knex.__req__` with the new request. This can happen if the handler yields the event loop before it queries.

E.g. request comes for `/foo` and while it awaits `something()`, a request comes for `/bar` causing the middleware to overwrite `__req__`. Then `/foo` runs `knex.select()` and the query is annotated with the wrong request:
```js
app.get('/foo', async (req, res) => {
  await something();
  const records = await knex.select(...);
  res.json(records);
});

app.get('/bar', async (req, res) => {
  const records = await knex.select(...);
  res.json(records);
});
```

### PR DESCRIPTION
**Pull request by omirho**
Fixes #24.

### CODE REVIEW

**Comment by balachandr** [comment]
@aabmass for review.

**Comment by aabmass** [comment]
I'm not super familiar with async hooks, but code makes sense to me. @omirho, were you able to verify it's working manually?

**Comment by lkonya** [comment]
Based on [NodeJS docs](https://nodejs.org/api/async_hooks.html#async_hooks_class_asynclocalstorage) AsyncLocalStorage is preferred over creating your own implementation on top of the async_hooks.

**Comment by lkonya** [comment]
Based on [NodeJS docs](https://nodejs.org/api/async_hooks.html#async_hooks_class_asynclocalstorage), they suggest to use AsyncLocalStorage, rather than creating your own implementation on top async-hooks. Though this is only available from 12.17. 
[node-execution-context](https://github.com/odedglas/node-execution-context) has an implementation to use AsyncLocalStorage when it is available or fall back to use async-hook if not.
Just thought worth mentioning it.

**Pull request merged**
